- config:
  numSigDigits: 5
  iternum: 1 
  outputLog: test.log
- name: test-EES-and-NL
  desc: Test if toggling EES or NL works correctly
  machine names: []
  inputDir: data/water_32M_10Ry/
  inputPar: cpaimd_config.p1
  inputPhy: water.input.min.$K
  outRef: ref-$K-p1.log
  keys: [ees-nl0l0, ees-nl0l1]
  numpe: [1]


