- config:
  numSigDigits: 5
  iternum: 1 
  outputLog: test.log
- name: test-numpes
  desc: Test if different number of PEs affects the results
  machine names: []
  inputDir: data/water_32M_10Ry/
  inputPar: cpaimd_config.sgrain-032.p1
  inputPhy: water.input.min.ees-nl1l1
  outRef: ref-ees-nl1l1-p1.log
  numpe: [2]

